<a href="https://colab.research.google.com/github/JanisJ2/jsc270-a4/blob/main/JSC270_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Github link: https://github.com/JanisJ2/jsc270-a4 \
Group member:
- Christoffer Tan (1008740445)
- Janis Joplin (10097515051)


In [115]:
# Import necessary modules
from google.colab import files
import io
import sys
import re

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

from scipy.cluster.hierarchy import dendrogram, linkage

import seaborn as sns

import nltk
nltk.download('punkt')  # Tokenizer
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem.porter import *

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [103]:
# Read the dataset from GitHub
!wget "https://raw.githubusercontent.com/JanisJ2/jsc270-a4/main/covid-tweets-train.csv"
!wget "https://raw.githubusercontent.com/JanisJ2/jsc270-a4/main/covid-tweets-test.csv"

--2024-03-24 20:56:17--  https://raw.githubusercontent.com/JanisJ2/jsc270-a4/main/covid-tweets-train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8991364 (8.6M) [text/plain]
Saving to: ‘covid-tweets-train.csv.3’

covid-tweets-train. 100%[===================>]   8.57M  --.-KB/s    in 0.09s   

2024-03-24 20:56:18 (97.9 MB/s) - ‘covid-tweets-train.csv.3’ saved [8991364/8991364]

--2024-03-24 20:56:18--  https://raw.githubusercontent.com/JanisJ2/jsc270-a4/main/covid-tweets-test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Lengt

In [104]:
# Read the train data from CSV file
train_data = pd.read_csv('covid-tweets-train.csv')
train_data.columns = ['Label', 'Message', 'Sentiment']
train_data.head()

Label                                            Message Sentiment
0      0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...         1
1      1  advice Talk to your neighbours family to excha...         2
2      2  Coronavirus Australia: Woolworths to give elde...         2
3      3  My food stock is not the only one which is emp...         2
4      4  Me, ready to go at supermarket during the #COV...         0

In [105]:
# Read the test data from CSV file
test_data = pd.read_csv('covid-tweets-test.csv')
test_data.columns = ['Label', 'Message', 'Sentiment']
test_data.head()

Label                                            Message  Sentiment
0      0  TRENDING: New Yorkers encounter empty supermar...          0
1      1  When I couldn't find hand sanitizer at Fred Me...          2
2      2  Find out how you can protect yourself and love...          2
3      3  #Panic buying hits #NewYork City as anxious sh...          0
4      4  #toiletpaper #dunnypaper #coronavirus #coronav...          1

# Part I

## a)

In [106]:
# Given the a data set, it will return the proportion of the observations belong the a sentiment type
def proportion_of_sentiment(data, sentiment_type):
    return (data['Sentiment'] == sentiment_type).sum() / len(data['Sentiment'])


for i in range(3):
    print(f"The proportion of the observations belong to sentiment type {i}: {proportion_of_sentiment(train_data, str(i))}")

The proportion of the observations belong to sentiment type 0: 0.374122220872312
The proportion of the observations belong to sentiment type 1: 0.18738913862228163
The proportion of the observations belong to sentiment type 2: 0.4383914469687766


## b)

In [107]:
def tokenize(data):
    data['Tokens'] = data['Message'].apply(nltk.word_tokenize)


tokenize(train_data)
print(train_data['Tokens'].head())

0    [@, MeNyrbie, @, Phil_Gahan, @, Chrisitv, http...
1    [advice, Talk, to, your, neighbours, family, t...
2    [Coronavirus, Australia, :, Woolworths, to, gi...
3    [My, food, stock, is, not, the, only, one, whi...
4    [Me, ,, ready, to, go, at, supermarket, during...
Name: Tokens, dtype: object


## c)

In [108]:
def remove_url(data):
    tokens_no_url = []

    # for the tokens of each row, remove all occurences of url
    for row in data['Tokens']:
        tokens_no_url.append([re.sub('^http', '', t) for t in row])

    # Replace our tokens with the url-removed version
    data['Tokens'] = tokens_no_url


remove_url(train_data)
train_data['Tokens'].head()

0    [@, MeNyrbie, @, Phil_Gahan, @, Chrisitv, s, :...
1    [advice, Talk, to, your, neighbours, family, t...
2    [Coronavirus, Australia, :, Woolworths, to, gi...
3    [My, food, stock, is, not, the, only, one, whi...
4    [Me, ,, ready, to, go, at, supermarket, during...
Name: Tokens, dtype: object

## d)

In [109]:
def remove_punctuation(data):
    tokens_no_punct = []
    # For the tokens of each row, remove all occurrences of punctuations (i.e. non-alphanumeric and non-whitespace)
    for row in data['Tokens']:
        tokens_no_punct.append([re.sub('[^\w\s]', '', t) for t in row])
    # Replace our tokens with the punctuation-removed version
    data['Tokens'] = tokens_no_punct

def convert_to_lowercase(data):
    lowercase_tokens = []
    # For the tokens of each row, convert all strings to lowercase
    for row in data['Tokens']:
        lowercase_tokens.append([t.lower() for t in row])
    # Replace our tokens with the lowercase version
    data['Tokens'] = lowercase_tokens


remove_punctuation(train_data)
convert_to_lowercase(train_data)
train_data['Tokens'].head()

0    [, menyrbie, , phil_gahan, , chrisitv, s, , tc...
1    [advice, talk, to, your, neighbours, family, t...
2    [coronavirus, australia, , woolworths, to, giv...
3    [my, food, stock, is, not, the, only, one, whi...
4    [me, , ready, to, go, at, supermarket, during,...
Name: Tokens, dtype: object

## e)

In [110]:
def stemming_tokens(data):
    ### Stemming our dataset using PorterStemmer
    stemmer = PorterStemmer()

    stemmed_tokens = []
    for row in data['Tokens']:
      stemmed_tokens.append([stemmer.stem(t) for t in row])

    data['Tokens'] = stemmed_tokens

stemming_tokens(train_data)
train_data['Tokens'].head()

0    [, menyrbi, , phil_gahan, , chrisitv, s, , tco...
1    [advic, talk, to, your, neighbour, famili, to,...
2    [coronaviru, australia, , woolworth, to, give,...
3    [my, food, stock, is, not, the, onli, one, whi...
4    [me, , readi, to, go, at, supermarket, dure, t...
Name: Tokens, dtype: object

## f)

In [111]:
def remove_stopwords(data):
    sw = stopwords.words('english')[:100]
    tokens_no_sw = []
    # For the tokens of each row, remove all occurrences of stopwords
    for row in data['Tokens']:
        tokens_no_sw.append([w for w in row if w not in sw])
    # Replace our tokens with the stopwords-removed version
    data['Tokens'] = tokens_no_sw


remove_stopwords(train_data)
train_data['Tokens'].head()

0    [, menyrbi, , phil_gahan, , chrisitv, s, , tco...
1    [advic, talk, neighbour, famili, exchang, phon...
2    [coronaviru, australia, , woolworth, give, eld...
3    [food, stock, not, onli, one, empti, , pleas, ...
4    [, readi, go, supermarket, dure, , covid19, ou...
Name: Tokens, dtype: object

## g)

In [135]:
def split_tokens_and_label(data):
    return data['Tokens'].to_numpy(), data['Label'].to_numpy()

def override_fcn(doc):
  # We expect a list of tokens as input
  return doc

def convert_to_vector(X):
    # Count Vectorizer
    count_vec = CountVectorizer(
        analyzer='word',
        tokenizer= override_fcn,
        preprocessor= override_fcn,
        token_pattern= None,
        max_features = 1000)

    # Remember this output is a Scipy Sparse Array
    counts = count_vec.fit_transform(X)
    print(counts.toarray())

    # Print this mapping as dictionary
    print(count_vec.vocabulary_)

    # Print the length of the vocabulary
    print(f'The length of the vocabulary is {len(count_vec.vocabulary_)}')

X, y = split_tokens_and_label(train_data)
convert_to_vector(X)

[[6 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [4 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]
{'': 0, 's': 739, 'advic': 38, 'talk': 866, 'famili': 331, 'phone': 634, 'number': 586, 'creat': 219, 'contact': 188, 'list': 499, 'school': 755, 'employ': 297, 'set': 774, 'onlin': 598, 'shop': 784, 'account': 27, 'suppli': 855, 'not': 580, 'order': 604, 'coronaviru': 197, 'australia': 80, 'give': 375, 'elderli': 293, 'disabl': 256, 'hour': 430, 'amid': 58, 'covid19': 212, 'outbreak': 607, 'food': 353, 'stock': 836, 'onli': 597, 'one': 596, 'empti': 299, 'pleas': 643, 'nt': 585, 'panic': 615, 'there': 879, 'will': 976, 'enough': 304, 'everyon': 315, 'take': 864, 'more': 558, 'than': 875, 'need': 570, 'stay': 828, 'calm': 131, 'safe': 740, 'covid_19': 215, 'readi': 694, 'go': 379, 'supermarket': 854, 'dure': 280, 'becaus': 96, 'm': 520, 'seriou': 770, 'thing': 883, 'caus': 147, 'shortag': 787, 'stayathom': 829, 'news': 573, 'first': 349, 'confirm': 185, 'case': 143, '